In [35]:
def normalize(X): 
     
    #function to normalize feature matrix, X 
    
    mins = np.min(X, axis = 0) 
    maxs = np.max(X, axis = 0) 
    rng = maxs - mins 
    norm_X = 1 - ((maxs - X)/rng) 
    return norm_X 

In [36]:
from sklearn import datasets, linear_model, metrics
import csv 
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
dataset = pd.read_csv('E:\College\Social_Network_Ads.csv')
dataset = pd.DataFrame(dataset)
dataset = dataset.drop(columns = ['User ID'])
dataset['Gender'] = dataset['Gender'].replace({'Female': 0, 'Male': 1})
dataset=np.array(dataset) 
X = normalize(dataset[:, :-1]) 
    
      
# stacking columns wth all ones in feature matrix 
X = np.hstack((np.matrix(np.ones(X.shape[0])).T, X))
print('\n')
print(X)

# response vector 
y = dataset[:, -1] 
# splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,
                                                    random_state=1)
 
# create logistic regression object
reg = linear_model.LogisticRegression()
 
# train the model using the training sets
reg.fit(X_train, y_train)

# making predictions on the testing set
y_pred = reg.predict(X_test)
 
# comparing actual response values (y_test) with predicted response values (y_pred)
print("Logistic Regression model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)



[[1.         1.         0.02380952 0.02962963]
 [1.         1.         0.4047619  0.03703704]
 [1.         0.         0.19047619 0.20740741]
 ...
 [1.         0.         0.76190476 0.03703704]
 [1.         1.         0.42857143 0.13333333]
 [1.         0.         0.73809524 0.15555556]]
Logistic Regression model accuracy(in %): 81.25


In [37]:
dataset

array([[    1,    19, 19000,     0],
       [    1,    35, 20000,     0],
       [    0,    26, 43000,     0],
       ...,
       [    0,    50, 20000,     1],
       [    1,    36, 33000,     0],
       [    0,    49, 36000,     1]], dtype=int64)

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)
 
predictions = logmodel.predict(x_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

              precision    recall  f1-score   support

           0       0.79      0.91      0.85        81
           1       0.82      0.61      0.70        51

    accuracy                           0.80       132
   macro avg       0.80      0.76      0.77       132
weighted avg       0.80      0.80      0.79       132

[[74  7]
 [20 31]]
0.7954545454545454


In [39]:
from sklearn import datasets, linear_model, metrics
 
# load the digit dataset
digits = datasets.load_digits()
 
# defining feature matrix(X) and response vector(y)
X = digits.data
y = digits.target

# splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,
                                                    random_state=1)
 
# create logistic regression object
reg = linear_model.LogisticRegression()
 
# train the model using the training sets
reg.fit(X_train, y_train)

# making predictions on the testing set
y_pred = reg.predict(X_test)
 
# comparing actual response values (y_test) with predicted response values (y_pred)
print("Logistic Regression model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)

Logistic Regression model accuracy(in %): 96.52294853963839


C:\Users\manas\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [40]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)
 
predictions = logmodel.predict(x_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        63
           1       0.95      0.95      0.95        59
           2       0.98      1.00      0.99        55
           3       0.97      0.96      0.96        68
           4       0.97      0.98      0.98        66
           5       0.96      0.90      0.93        52
           6       1.00      1.00      1.00        54
           7       0.98      0.95      0.97        62
           8       0.89      0.98      0.93        51
           9       0.95      0.94      0.94        64

    accuracy                           0.97       594
   macro avg       0.97      0.97      0.97       594
weighted avg       0.97      0.97      0.97       594

[[63  0  0  0  0  0  0  0  0  0]
 [ 0 56  0  0  1  0  0  0  2  0]
 [ 0  0 55  0  0  0  0  0  0  0]
 [ 0  0  0 65  0  0  0  1  2  0]
 [ 0  1  0  0 65  0  0  0  0  0]
 [ 0  1  1  1  0 47  0  0  0  2]
 [ 0  0  0  0  0  0 54  0  0  0]
 [ 0  0  0

C:\Users\manas\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [41]:
print(confusion_matrix(y_test, predictions))


[[63  0  0  0  0  0  0  0  0  0]
 [ 0 56  0  0  1  0  0  0  2  0]
 [ 0  0 55  0  0  0  0  0  0  0]
 [ 0  0  0 65  0  0  0  1  2  0]
 [ 0  1  0  0 65  0  0  0  0  0]
 [ 0  1  1  1  0 47  0  0  0  2]
 [ 0  0  0  0  0  0 54  0  0  0]
 [ 0  0  0  1  1  0  0 59  0  1]
 [ 0  0  0  0  0  1  0  0 50  0]
 [ 0  1  0  0  0  1  0  0  2 60]]
